name: Deploy GitHub Pages from _site

on:
  push:
    branches: [main]
    paths:
      - "_site/**"
  workflow_dispatch: {}

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  upload:
    name: Upload _site as Pages artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Verify _site presence
        run: |
          test -d _site || { echo "_site nicht vorhanden – nichts zu deployen"; exit 1; }
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: upload
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
